/** 성별 */
export enum FastTrackGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

/** 기관 유형 */
export enum FastTrackInstitutionType {
  CHILD_CARE_FACILITY = 'CHILD_CARE_FACILITY',
  GROUP_HOME = 'GROUP_HOME',
  COMMUNITY_CHILD_CENTER = 'COMMUNITY_CHILD_CENTER',
  OTHER = 'OTHER',
}

/** 보호자 연락 가능여부 */
export enum FastTrackGuardianContactAvailability {
  AVAILABLE = 'AVAILABLE',
  LIMITED = 'LIMITED',
  UNAVAILABLE = 'UNAVAILABLE',
}

/** 위기 수준 항목 */
export enum FastTrackCrisisLevel {
  SELF_HARM_OR_SUICIDE = 'SELF_HARM_OR_SUICIDE',
  SEVERE_DEPRESSION_OR_LETHARGY = 'SEVERE_DEPRESSION_OR_LETHARGY',
  AGGRESSIVE_BEHAVIOR_OR_IMPULSE_CONTROL = 'AGGRESSIVE_BEHAVIOR_OR_IMPULSE_CONTROL',
  PEER_CONFLICT_OR_ISOLATION = 'PEER_CONFLICT_OR_ISOLATION',
  SCHOOL_MALADJUSTMENT_OR_REFUSAL = 'SCHOOL_MALADJUSTMENT_OR_REFUSAL',
  REPEATED_RUNAWAY_ATTEMPTS = 'REPEATED_RUNAWAY_ATTEMPTS',
  SUSPECTED_ABUSE = 'SUSPECTED_ABUSE',
  OTHER = 'OTHER',
}

/** 보호자 동의 여부 */
export enum FastTrackGuardianConsentStatus {
  AGREED = 'AGREED',
  NOT_AGREED = 'NOT_AGREED',
}

/** Fast-track 의뢰 처리 상태 */
export enum FastTrackReferralStatus {
  SUBMITTED = 'SUBMITTED',
  REVIEWING = 'REVIEWING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
